### ISSUE TITLE
own NPM package

### ISSUE THREAD

**Issue by williamdes** [code-lts/jquery-fullscreen-plugin#38]
https://www.npmjs.com/package/jquery-fullscreen-plugin

**Comment by williamdes** [comment]
@skecskes After this repository changed namespace could you add me to the uploaders of the NPM package ?

Ref: https://github.com/code-lts/jquery-fullscreen-plugin/pull/37#issuecomment-620105516

**Comment by skecskes** [comment]
sure. I'm happy that somebody is taking it over. What is your username on npm?

**Comment by williamdes** [comment]
Thank you :)
https://www.npmjs.com/~williamdes

**Comment by skecskes** [comment]
there you go. let me know if you need any help 👍

**Comment by williamdes** [comment]
For now I can not access settings but I will wait ;)

**Comment by williamdes** [comment]
I works :tada: 
Do you mind to be removed ?
